name: '@openng/cashew'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install

      - name: Test
        run: pnpm run test:lib

      - name: Test Schematics
        run: pnpm run test:schematics

      - name: Build
        run: pnpm run build:lib

      - name: Build Playground
        run: pnpm run build
